FROM centos

RUN yum -y install epel-release \
    && yum -y update

RUN rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm \
    && rpm --import http://rpms.famillecollet.com/RPM-GPG-KEY-remi \
    && yum-config-manager --enable epel,remi-php73,remi 

RUN rpm -ivh https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm

RUN yum -y install --enablerepo=epel,remi,remi-php73 php php-mbstring php-gd php-soap php-pear php-xml php-pdo php-pgsql php-pecl-zip \
    && yum -y install net-snmp supervisor \
    && yum -y install zabbix-server-pgsql zabbix-web-pgsql zabbix-web-japanese \
    && yum -y install zabbix-agent zabbix-get \
    && rm -rf /var/cache/yum/

EXPOSE 80/TCP 443/TCP

COPY ["zabbix.conf", "/etc/httpd/conf.d/"]
COPY ["99-zabbix.ini", "/etc/php.d/"]
COPY supervisord.conf /etc/
ENTRYPOINT ["/usr/bin/supervisord"]
